# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=AccountResponse:id=id,balance=balance
TransferRequest=TransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
UpdateProfileRequest=UserProfileUpdateResponse:name=customer.name