### Get auth token admin token YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Positive test Create user 1 by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
"username": "Ayrat1",
"password": "Ayrat12345@",
"role": "USER"
}


### Логин User 1 Basic QXlyYXQxOkF5cmF0MTIzNDVA
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json


{
  "username": "Ayrat1",
  "password": "Ayrat12345@"
}

### Positive test Authorized user 1 can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{}



### Позитивный тест получение значение по умолчанию для валидного токена юзера 1
GET http://localhost:4111/api/v1/accounts/2/transactions
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{}


### Create user 2 by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
"username": "Ayrat2",
"password": "Ayrat12@",
"role": "USER"
}


### Логин User 2 Basic QXlyYXQyOkF5cmF0MTJA
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json


{
  "username": "Ayrat2",
  "password": "Ayrat12@"
}


### Authorized user 2 can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/x-www-form-urlencoded
Authorization: Basic QXlyYXQyOkF5cmF0MTJA

{}



### Позитивный тест получение значение историй транзации по умолчанию для юзера 2
GET http://localhost:4111/api/v1/accounts/3/transactions
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQyOkF5cmF0MTJA

### Позитивный тест получение значение историй транзации по  юзера 1
GET http://localhost:4111/api/v1/accounts/2/transactions
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

### Позитивный тест Проверка начислений на депозит 1000 уе, юзера 2
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQyOkF5cmF0MTJA

{
  "id": 3,
  "balance": 1000
}

### Позитивный тест Проверка максимального значения начислений на депозит 5000 уе, юзера 1
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "id": 2,
  "balance": 5000
}

### Негативный тест Проверка максимального значения начислений на депозит 5001 уе, юзера 1
// По ТЗ - Максимальная сумма депозита 5000 тест упал, но депозит стал 10001
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "id": 2,
  "balance": 5001
}


### Негативный тест отрицательная сумма юзер 1
// По ТЗ - 400 ошибка - ок
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "id": 2,
  "balance": -1
}

### Негативный тест депозит на чужой аккаунт
// По ТЗ - 400 ошибка - ок
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "id": 3,
  "balance": 1
}

### Негативный тест депозит 0
// ответ 400 но депозит может быть = 0
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "id": 2,
  "balance": 0
}


### Позитивный кеис трансфер от U1 на U2 мин суммы 1 ye
// ответ 200
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 1
}


### Позитивный кеис трансфер от U1 на U2 макс суммы 10000 ye
// ответ 200
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 10000
}


### Позитивный тест проверка транзации изера 2
//200 ок
GET http://localhost:4111/api/v1/accounts/3/transactions
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQyOkF5cmF0MTJA


### Негативный кеис трансфер от U1 на U2 макс суммы 10001 ye
// ответ 200 ок Ожидаем ошибку 400
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 10001
}


### Негативный кеис трансфер от U1 на U2 макс суммы больше значения баланса 50000 ye
// Ожидаем ошибку 400
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 50001
}

### Негативный кеис трансфер от U1 на U2 макс отрицательной суммы -1000
// Ожидаем ошибку 400
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": -1000
}

### Позитивный кеис изменение профиля для U1
// Ожидаем 200 - ок
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "name": "New Ayrat2"
}

### Позитивный кеис изменение минимальное значение для поля Имя профиля U1
// Ожидаем 200 - ок 1 - символ ок цифра не ок
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "name": "2"
}

### Позитивный кеис изменение максимальное значение = 15 для поля Имя профиля U1
// Ожидаем 200
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "name": "йцукенгшщзхъфыв"
}

### Негативный кеис изменение максимальное значение = 16 для поля Имя профиля U1
// Ожидаем 400 - тест не прошел
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "name": "йцукенгшщзхъфывв"
}

### Негативный кеис изменение пустое значение для поля Имя профиля U1
// Ожидаем 400 - тест не прошел
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{
  "name": ""
}

### Негативный кеис изменение без поля Имя профиля U1
// Ожидаем 400 - тест не прошел
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQxOkF5cmF0MTIzNDVA

{}

### Негативный тест Проверка начислений на депозит 1000 уе, юзера 2 неверным методом
//405 - ок
PUT http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Accept: application/json
Authorization: Basic QXlyYXQyOkF5cmF0MTJA

{
  "id": 3,
  "balance": 1000
}